### ISSUE TITLE
How to train it by gpu?

### ISSUE THREAD

**Issue by ZZy129326999** [kwea123/MINER_pl#1]
Excuse me, how to train with GPU? I am getting an error when using the GPU.
![image](https://user-images.githubusercontent.com/72543018/195551918-cfbe96ee-a1d0-4f86-837b-d39f18d95822.png)

**Comment by kwea123** [comment]
what is your command? the example command in the readme should work, you just need to replace the image path

**Comment by ZZy129326999** [comment]
I test torch-v1.12, it does not work. But I test 1.11, it works! Thanks to your perfect work!!!!! Thank you! But I still want to know case, why?

**Comment by fusheng-ji** [comment]
@ZZy129326999  Thanks, perfect solution.

**Comment by ZZy129326999** [comment]
> 

Cheer up !

**Comment by kwea123** [comment]
Maybe the current pytorch-lightning doesn't support pytorch 1.12 yet (I believe it will be supported soon), I will update the readme, thank you for the report!
