### ISSUE TITLE
如何保存图片

### ISSUE THREAD

**Issue by zouchen92** [kwea123/MINER_pl#3]
安安葵
请问如何才能保存训练后重建的图片
我运行完Pluto example，只得到了PSNR : 45.1094 dB ，但是没有看到重建的图片
log_image的default改成了True，但是在服务器的GPU上运行完，也没有保存图片

**Comment by kwea123** [comment]
`log_image` saves prediction to tensorboard, if you want to save to disk (as .png), please modify here https://github.com/kwea123/MINER_pl/blob/84c089f097890a13b59d5d4ca17ca79f39d707e0/train.py#L215
this variable is the final prediction, you can pass it to `.cpu().numpy()` then save it.

**Comment by zouchen92** [comment]
Thank you
